openapi: 3.0.0
info:
  title: Documentación de la API ZANID
  version: 1.0.0
paths:
  /users:
    get:
      summary: Obtener lista de usuarios
      tags:
        - Usuarios
      security:
        - has-permission: [MANAGE_USERS]
      responses:
        '200':
          description: OK
    /{userID}/permissions:
      get:
        summary: Obtener permisos de usuario
        tags:
          - Permisos
        parameters:
          - name: userID
            in: path
            description: ID de usuario
            required: true
            schema:
              type: string
        responses:
          '200':
            description: OK
      post:
        summary: Agregar permiso a usuario
        tags:
          - Permisos
        parameters:
          - name: userID
            in: path
            description: ID de usuario
            required: true
            schema:
              type: string
        responses:
          '200':
            description: OK
      delete:
        summary: Eliminar permiso de usuario
        tags:
          - Permisos
        parameters:
          - name: userID
            in: path
            description: ID de usuario
            required: true
            schema:
              type: string
        responses:
          '200':
            description: OK